### ISSUE TITLE
Performance based restart script?

### ISSUE THREAD

**Issue by codexGW** [soulkobk/ArmA_Scripts#2]
Hey soulkobk I was wondering what your thoughts would be on converting your serverRestartMessages script to a performance based restart script? I might be able to do it with enough time but its a bit over my head. I was thinking a restart script that will use checks for server up time and server FPS. Something with 4 or 5 conditional statements based on both. 

```
If server up time equals 3 hours and server FPS is below 15 then start a 20 minute server restart with messages.
If server up time equals 4 hours and server FPS is below 19 then start a 20 minute server restart with messages.
If server up time equals 5 hours and server FPS is below 25 then start a 20 minute server restart with messages.
If server up time equals 6 hours and server FPS is below 35 then start a 20 minute server restart with messages.
```

Its just a idea I had and I will try to see what I can do this weekend.

**Comment by soulkobk** [comment]
Hi, currently I'm not interested in converting what I already have written.

What you suggest would able to be achieved though by using a multi array for the hours up-time versus current server fps ([[3,15],[4,19][5,25],[6,35]] etc), if the criteria matches or is over the threshold on any-given-loop, then trigger a 20 minute 'warning' count down.

It shouldn't be too hard, and you have my code as a reference, so it's a good starting point. Good luck with it.

-soul.

**Comment by codexGW** [comment]
Thanks for the reply soul. I'll try to Frankenstein yours into this. I'll let you know how it goes.

**Comment by codexGW** [comment]
Got around to this finally. Took me a day with testing. Works well. To me, a restart based on performance with uptime really seems like a no brainer. This is really good for those low pop servers that get swamped on the weekends.
https://github.com/A3Armory/perfRestart/blob/master/perfServerRestart.sqf

**Comment by soulkobk** [comment]
Nice one Gigatek, glad you got it sorted, I'll be sure to check it out at some stage.
